version: '3.8'

services:
  wordpress:
    build: .
    container_name: wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html


  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes:
      - ./wordpress:/var/www/html
    #  - ./wp-cli.yml:/var/www/html/wp-cli.yml
    working_dir: /var/www/html
    entrypoint: ["sh", "-c"]
    command: "while true; do sleep 1000; done"


volumes:
  db_data:
